[platformio]
build_dir = C:\pio_build

; ============================================================
;  PlatformIO – Notificador de Catedráticos ULSA
;  ESP32 DevKit V1
; ============================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ── Configuración de subida ──
upload_speed = 921600
upload_port = COM9

; ── Librerías ──
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
    dfrobot/DFRobotDFPlayerMini